config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy] 
      resources :likes, only: [:create]
    end
  end

  get '/likes/:id/create', to: 'likes#create', as: 'increment_likes'

  namespace :api, defaults: { format: :json } do
    resources :sessions
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_post_counter

  private

  def update_post_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_user_and_post

  def new
    @like = Like.new
  end

  def create
    @like = Like.new(user: current_user, post: @post)

    if @like.save
      redirect_to user_post_path(@user, @post), notice: 'Post liked successfully.'
    else
      render :new
    end
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_form.html.erb
<%= form_with(model: [@user, @post, @like], url: user_post_likes_path(@user, @post), method: :post) do |form| %>
  <div class="actions">
    <%= form.submit 'Like', class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/likes/new.html.erb
<%= form_with(model: @like, url: user_post_likes_path(@user, @post), method: :post) do |form| %>
  <div class="actions">
    <%= form.submit 'Like' %>
  </div>
<% end %>