config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy] 
      resources :likes, only: [:create]
    end
  end

  get '/likes/:id/create', to: 'likes#create', as: 'increment_likes'

  namespace :api, defaults: { format: :json } do
    resources :sessions
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :user_id, dependent: :destroy
  has_many :likes, foreign_key: :user_id, dependent: :destroy

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  # Validaciones
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :bio, :photo, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :bio, :photo, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1 class="mt-2"> Adventures in Writing's  Users</h1>
      <p class="lead">Here you can see all the users of the blog.</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% @users.each do |user| %>
        <div class="my-3 row">
          <div class="col-12 col-sm-3 col-md-2 col-lg-2 col-xl-2 d-none d-sm-block">
            <div class="user-photo">
              <img class="pic-shadow" src="<%= user.photo %>" alt="User Photo">
            </div>
          </div>
          <div class="col-12 col-sm-9 col-md-10 col-lg-10 col-xl-10">
            <div class="d-flex align-items-center h-100 custom-border py-1 px-3">
              <div class="user-info w-100">
                <h5 class="user-name">
                  <%= link_to user.name, user_path(user), title:"To User Details", class: "unstyled" %> 
                </h5>
                <p class="user-posts text-end m-0">
                  Number of posts: <%= user.posts_counter %>  
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="mt-2">User Details</h1>
      <p class="lead">Here you can see all the users of the blog.</p>
    </div>
  </div>  
  
  <div class="row">
    <div class="col-12 col-sm-3 col-md-2 col-lg-2 col-xl-2 d-none d-sm-block">
      <div class=" user-photo">
        <img class="pic-shadow" src="<%= @user.photo %>" alt="User Photo">
      </div>
    </div>
    <div class="col-12 col-sm-9 col-md-10 col-lg-10 col-xl-10">
      <div class="d-flex align-items-center h-100 custom-border py-1 px-3">
        <div class="p-3 user-info w-100">
          <h5 class="unstyled user-name">
             <%= @user.name %> 
          </h5>
          <p class="user-posts text-end m-0">
            <a href="<%= user_posts_path(@user) %>" title="To User Posts" class="unstyled">See All Post</a> <br>
             <%= link_to 'New Post', new_user_post_path(@user), class: 'btn btn-success my-2 text-center' %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 custom-border rounded my-3">
      <h5 class="user-name py-3">
        <%= @user.name %> Bio
      </h5>
      <p class="user-name">
        <%= @user.bio %>
      </p>
    </div>
  </div>

<div class="row">
  <h5 class="user-name">
    Most Recent Posts:
  </h5>
  <% recent_posts = @user.recent_posts %>
  <% if recent_posts.any? %>
    <% recent_posts.each do |post| %>
      <div class="col-sm-12 custom-border rounded my-3">
        <h5 class="user-name py-3">
           <%= link_to "Post #{post.id}", user_post_path(user_id: @user.id, id: post.id), title: "To Post Details", class:"unstyled"%>
        </h5>
        <h3 class="user-name">
          <%= post.title %>
        </h3>
        <p class="user-name">
          <%= post.text %>
        </p>
        <div class="text-end">
          <p><%= post.comments.count %> comments</p>
          <p><%= post.likes.count %> Likes</p>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="custom-border py-2">No recent posts</p>
  <% end %>
</div>

  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-around my-3 text-center">
        <%= link_to "See all users", users_path(@user), class: "btn btn-dark" %>
        <%= link_to "See all posts", user_posts_path(@user), class: "btn btn-dark all-post" %>
      </div>
    </div>
  </div>
</div>